name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
        push: true
        tags: latest
        github-token: ${{ github.token }}
          
